sudo: required
language: java
jdk: oraclejdk8
services:
  - docker

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent

cache:
  directories:
  - '$HOME/.m2/repository'
