sudo: required

language: ruby

services:
  - docker
  
before_install:
    - docker pull carlad/sinatra
    - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
    - docker build -t najlabioinfo/:latest .
    - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
    - docker run  -it najlabioinfo/springb-reactjs-postgres:latest -c "cd najlabioinfo/springsampling; java -jar target/springsampling-0.0.1-SNAPSHOT.jar;"