# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-browsers

      - image: circleci/postgres:9.4
      # some containers require setting environment variables
      environment:
        POSTGRES_USER: root

      # Create Postgres users and database
      # Note the YAML heredoc '|' for nicer formatting
      - run: |
          sudo -u root createuser -h localhost --superuser simplifyuser &&
          sudo createdb -h localhost samplificatordb
          sudo -u postgres psql -c "ALTER USER simplifyuser PASSWORD 'samplifypass';"
      - image: circleci/node:4.8.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn --fail-never dependency:go-offline || true

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
- run: mvn test jacoco:report coveralls:report -Dskip.yarn
